name: "Pre-commit checks"

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonbabenko/pre-commit-terraform:v1.62.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init tflint
        run: tflint --init
      - name: Run pre-commit checks
        run: pre-commit run -a
